### ISSUE TITLE
IltaPlus not working anymore due to API changes

### ISSUE THREAD

**Issue by eioo** [Hakorr/Userscripts#14]
Seems like they finally updated their API endpoint `https://api.il.fi/v1/articles/<article-id>?include_main_media=true` not to include the full articles.

**Comment by Hakorr** [comment]
Yup, Iltashit strikes back :(

They did it about a week ago, I guess someone either alerted Iltalehti about this or some employee found it, since the userscript was shared on Ylilauta and other social medias, gaining attention. The userscript had worked since 2021 since it was a bit underground until now.

I did not find any ways to bypass it for now. I'd need a real IltaPlus account to check how they authenticate the request, but I'm guessing they did it properly this time and there's no way to bypass it anymore.
