### ISSUE TITLE
Opening in a new tab

### ISSUE THREAD

**Issue by Alin6004** [Hakorr/Userscripts#6]
How do I change it so it opens in a new window instead of a tab?

**Comment by Hakorr** [comment]
That was initially the plan, however I noticed some browsers broke the GUI by telling it wrong screen dimensions (I guess as a privacy measure). I think I could add a setting to enable that feature, though.

**Comment by Alin6004** [comment]
Thanks! And have you thought of always having it on whenever you go back to lobby?

**Comment by Hakorr** [comment]
> always having it on whenever you go back to lobby?

Good question! The GUI's window stays open as long as it can. Due to the popup window limitations, it cannot be accessed after you load a new page (e.g. the lobby), therefore keeping it open would not serve any purpose.

This too I considered while making the userscript, and have thought of many alternative ways to do this. If I get anything working, I'll be sure to use it in the future.
